#!/usr/bin/env node
console.log(process.argv);

/**
 * Module dependencies.
 */

console.log("Choose: (-r, -s, -h, -c)");

var program = require('commander');

program
  .version('0.0.1')
  .option('-r, --rain', 'It is raining')
  .option('-s, --snow', 'It is snowing')
  .option('-h, --hot', 'It is hot')
  .option('-c, --cold', 'It is cold')
//  .option('-c, --cold [type]', 'Add the specified type of cheese [marble]', 'marble')
  .parse(process.argv);

console.log('The weather in Portland is: ');

if (program.rain) console.log('  - rain');
if (program.snow) console.log('  - snow');
if (program.hot) console.log('  - hot');
if (program.cold) console.log('  - cold');

//console.log('  - %s cheese', program.cheese);

